export const SET_LOCATIONS = 'SET_LOCATIONS'
export const ADD_LOCATION_TO_LOCATIONS = 'ADD_LOCATION_TO_LOCATIONS'
export const SET_LAT_TEXT = 'SET_LAT_TEXT'
export const SET_LONG_TEXT = 'SET_LONG_TEXT'
